### ISSUE TITLE
segfault when trying to install file transfer app

### ISSUE THREAD

**Issue by akkartik** [mempko/firestr#11]
I compiled firestr from source (git hash 88aa7d8ae1317fae1ab6a2eb7d2eb593b63768de) on my thinkpad running ubuntu 14.04.1. When I dragged the transfer.fab app to the window my whole machine seized up for a few seconds and then firestr died with a segfault.  Here's the output, fwiw.

```
QWidget::setWindowModified: The window title does not contain a '[*]' placeholder
QWidget::setWindowModified: The window title does not contain a '[*]' placeholder
...
QWidget::setWindowModified: The window title does not contain a '[*]' placeholder
QWidget::setWindowModified: The window title does not contain a '[*]' placeholder
zsh: segmentation fault  ./src/firestr/firestr
./src/firestr/firestr  22.72s user 4.56s system 1% cpu 35:45.00 total
```

**Comment by mempko** [comment]
Thanks, I will try to replicate and fix tonight.

**Comment by akkartik** [comment]
Let me know if you need version numbers for any of the dependencies. Though ubuntu installed a ton of packages for each top-level `apt-get install`.

**Comment by mempko** [comment]
I tried to replicate the segfault on ubuntu 14.04.01 and could not do it. Do you remember the steps you took to do it? 

What I did was create a new user, then drag the transfer.fab file into firestr.
Did you have contacts, or other apps already installed?

**Comment by akkartik** [comment]
Just a couple of users, no other apps.

I'll try to install another app in a few hours, and report what happens.

**Comment by akkartik** [comment]
I added the `pong` app and it seemed to install without problems. When I tried to play it, though: segfault.

(I updated so I'm now at hash 53ad4351ddab)

**Comment by akkartik** [comment]
After a restart it came up fine, no problems.

**Comment by mempko** [comment]
Ok, I will try to replicate again. When you tried to use the app, were you in a conversation with another? 

Also, can you recreate the segfault and then under your home directory, can you paste me the last bit of lines in ~/.config/firestr/log/out.log

**Comment by akkartik** [comment]
Ah that is good to know. But sadly I am unable to get another segfault. I tried installing the draw app, and I also tried uninstalling and reinstalling the transfer and pong apps that segfaulted last time.

I'll keep an eye out. My friends have been seeing more segfaults than me, on mac os and on ubuntu. I've asked them to create new issues with details.

**Comment by mempko** [comment]
Here is a stupid question, your friends are using version 0.8 right? You can see the version in the about dialog in the main menu.

**Comment by akkartik** [comment]
Yeah we just downloaded the app the day I first pinged you.

**Comment by mempko** [comment]
@akkartik I made several fixes. Have you tried the latest version?

**Comment by mempko** [comment]
Since there has been no update and I was not able to recreate it. I am closing this issue.
