### ISSUE TITLE
Unable to run the application on windows 7(32 bit)

### ISSUE THREAD

**Issue by AforAvi** [mempko/firestr#12]
Hi,

I came across this error while trying to run the application, could you please help?

![error](https://cloud.githubusercontent.com/assets/288093/7336215/64357f1a-ec0e-11e4-8818-ad6ea57457c0.png)

**Comment by mempko** [comment]
I currently only have a build for 64bit windows. I don't have one for 32bit windows. 
I don't have 32bit windows machine I can build on at the moment.

I will try to find someone who has a 32bit windows system to have them build a version for it.
