### ISSUE TITLE
Luakit?

### ISSUE THREAD

**Issue by o-jasper** [mempko/firestr#16]
I have been wanting to implement, pretty close to the idea you have with luakit. Simply for the gui this might have advantages:

* Many people know HTML-related tech, this means they can modify/create things for it.
  + It is.. "evolved far". CSS could make some kinds of customization easy too.
  + It suggests a template-based system where people can change bits of template for customization.
  + Customization can easily be used to make mobile-oriented guis.
  + (edit)Amenable to using web-technologies locally.
* Chrome pages can be turned into server-able pages. (potentially disadvantage when people foolishly use centralized services with this thing)
* It ties it into the browser.
  + Addons immediately operate on any of the pages.
  + If Ethereum API is ffi-ed in, the same javascript bindings can be exposed as Ethereum. A lot could potentially work seamlessly with it.
  + Ties it into URIs. You could make a lot of things into uris, like locations in pdf, video files, identifying files by magnet links.(/checksums, sortah same) 

Some disadvantages, like security not 100% sure all the tiem. I am still hesitant to potentially expose sql-queries to it.(which would potentiallyhappen if bookmark queries had URIs) Sqlites inbuild `?` thingies presumably protect...  Also a disadvantage is that potentially exposing to some injections of nasty javascript, like sending a message with `<script>...</script>` in it, and a bug allows it through, leading to potential phishing-like stuff or something. (dont know of a tag that is there just to disable html inside? Template would just end the tag itself i guess.. Setting all of them with `.innerText` would be a bit of a PITA.. and what if i want markdown....)

The way what i want to do is similar; i want to make a F2F network, and people can write lua code to create communication channels. I want it to be a bit agnostic about that, though initially i'd use Tox. Channels should give out some indication of reliability/latency. Based on that, people hold messages for their friends, send messages directly, and keep data from what is inferred to be interesting. It'd also need a way to query the F2F network for information out that. Thinking a bloom filter of stuff already obtained and a friend at a time. For instance, for a "decentralized reddit" you'd query for comments on a URI. (or a URI + "subreddit") Searching friends-of-friends could really help keep out shills. (Implied though is that it'd need a bit of a reputation/trust system) (Except for the bloom filter, [had this idea for a while](https://github.com/o-jasper/gpgshare))

Since i wanted to start with Tox, i wanted to make an IM client. I wanted it to be nice, with a good search(in chats/messages/contacts) and stuff, so made a [fairly general sql searcher](https://github.com/o-jasper/o-jasper-luakit-stuff/tree/master/listview), from that first an alternative bookmarks/history.(including tags and stuff, and `site:` like stuff) I guess that is very early part of the project, since i have yet to figure out how to incorporate different kinds of communication. (which to choose, largely)

**Comment by mempko** [comment]
Firestr is designed that the backend is gui agnostic. Right now the lua apps in Firestr run in their own thread and communicate with the gui through an interface via message passing. 

The current GUI is Qt, and my goal with the design is that people could use other GUI frameworks and design other clients. For example, I wanted to have a QtQuick client so I can make a phone port.

A webkit/HTML GUI is an interesting idea and should be feasible. If someone wanted to implement one, I would not be against it. Of course there would need to be a way to make sure that Qt and HTML clients are compatible and maybe having a runtime check for apps and making sure that the Qt and HTML client both implement the baseline lua api I have now, it should work. 

Your Tox IM client sounds cool and keep on keeping on and you will build it.
