### ISSUE TITLE
validity of 'firestr_0.11.dmg'

### ISSUE THREAD

**Issue by core-code** [mempko/firestr#22]
hey there,

when firestr_0.11.dmg was first posted, it had the checksum
7d7d3740b2eb5a78bc8573b24cdc47c15bcd6536e21f0e8e82722b8a7e8e8cf3

now it suddenly has the checksum
01bc1cda3f12b1bf510b668ad437f6cdbe2db3bd249d8840367569becd7df952

since the file was silently updated without explanation and has no codesigning in-place to confirm its authenticity, its hard to confirm whether it is a valid release or whether it has been tampered with.

could you give any confirmation about the validity of the file?

many thanks

**Comment by mempko** [comment]
I updated the signature here http://mempko.com/firestr/build/0.11/ to the file. Use the firestr_0.11.dmg.sig file there to verify your copy.

I also attached the sig file here for your convenience. Replace .txt with .sig  

[firestr_0.11.dmg.txt](https://github.com/mempko/firestr/files/3027727/firestr_0.11.dmg.txt)

**Comment by core-code** [comment]
thank you!
